# Generated by Django 6.1.1 on 2026-09-30 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo_carrera', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=50)),
                ('plan_vigente', models.CharField(max_length=8)),
                ('escuela', models.CharField(max_length=100)),
                ('resolucion_nacional', models.CharField(blank=True, max_length=8, null=True)),
                ('notas', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CarerraResolucionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_institucional', models.CharField(max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_relacionadas', to='academico.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='CarreraNombreTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulos', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombresTitulos', to='academico.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('legajo_graduado', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('dni_graduado', models.CharField(max_length=9, unique=True)),
                ('fecha_ingreso_universidad', models.DateField()),
                ('promedio_sin_aplazo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promedio_con_aplazo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('promedio_sin_aplazo__gte', 1), ('promedio_sin_aplazo__lte', 10)), name='promedio_sin_aplazo'), models.CheckConstraint(condition=models.Q(('promedio_con_aplazo__isnull', True), models.Q(('promedio_con_aplazo__gte', 1), ('promedio_con_aplazo__lte', 10)), _connector='OR'), name='promedio_con_aplazo')],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('tipo', models.CharField(choices=[('EQUIV', 'Equivalencia'), ('EXAM', 'Examen')], default='EXAM', max_length=20)),
                ('acta_respaldatoria', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_examen', models.DateField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenGraduado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduados_asociados', to='academico.examen')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_asociados', to='academico.graduado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('examen', 'graduado'), name='unique_examen_graduado'), models.CheckConstraint(condition=models.Q(('nota__gte', 1), ('nota__lte', 10)), name='notra_entre_uno_y_diez')],
            },
        ),
        migrations.CreateModel(
            name='Analitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_secundario', models.CharField(max_length=200, null=True)),
                ('provincia_secundario', models.CharField(max_length=200, null=True)),
                ('nombre_secundario', models.CharField(max_length=200, null=True)),
                ('titulo_secundario', models.CharField(max_length=200, null=True)),
                ('fecha_egreso_carrera', models.DateField()),
                ('titulo_carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analiticos', to='academico.carreranombretitulo')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analiticos', to='academico.graduado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graduado', 'titulo_carrera'), name='fk_analitico')],
            },
        ),
        migrations.CreateModel(
            name='GraduadoApellido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apellidos_asociados', to='academico.graduado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('apellido', 'graduado'), name='unique_apellido_graduado')],
            },
        ),
        migrations.CreateModel(
            name='GraduadoCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_carrera', models.DateField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduados_asociados', to='academico.carrera')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_asociadas', to='academico.graduado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graduado', 'carrera'), name='unique_graduado_carrera')],
            },
        ),
        migrations.CreateModel(
            name='GraduadoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_asociados', to='academico.graduado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nombre', 'graduado'), name='unique_nombre_graduado')],
            },
        ),
        migrations.CreateModel(
            name='GraduadoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asociadas', to='academico.graduado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduados_asociados', to='academico.materia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graduado', 'materia'), name='unique_graduado_materia')],
            },
        ),
        migrations.CreateModel(
            name='CarreraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asociadas', to='academico.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_asociadas', to='academico.materia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('materia', 'carrera'), name='unique_carrera_materia')],
            },
        ),
    ]
