# Generated by Django 6.1.1 on 2026-10-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_plan', models.CharField(max_length=10)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='carreramateria',
            name='unique_carrera_materia',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='plan_vigente',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='orden',
        ),
        migrations.AddField(
            model_name='planestudios',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='academico.carrera'),
        ),
        migrations.AddField(
            model_name='planmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_asociadas', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='planmateria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asociadas', to='academico.planestudios'),
        ),
        migrations.RemoveField(
            model_name='carreramateria',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='carreramateria',
            name='materia',
        ),
        migrations.AddConstraint(
            model_name='planestudios',
            constraint=models.UniqueConstraint(fields=('carrera',), name='fk_plan_carrera'),
        ),
        migrations.AddConstraint(
            model_name='planmateria',
            constraint=models.UniqueConstraint(fields=('materia', 'plan'), name='unique_plan_materia'),
        ),
        migrations.DeleteModel(
            name='CarreraMateria',
        ),
    ]
